### ISSUE TITLE
搜索框清除按钮

### ISSUE THREAD

**Issue by cyio** [cyio/bch123.org#3]
https://github.com/necolas/normalize.css/issues/685

macos 下，chrome 和 safari 会显示清除按钮，为了统一，normalize 把这个去掉了
这种情形，确实应该先去掉，然后由设计者考虑是否要添加这外按钮

```css
/**
 * Remove the inner padding and cancel buttons in Chrome and Safari on macOS.
 */

[type="search"]::-webkit-search-cancel-button,
[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}
```

手动实现
[HTML Textbox with a clear button in Pure CSS and without JavaScript](https://codepen.io/shidhincr/pen/ICLBD)
